CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE auth_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL DEFAULT '0'
);

CREATE TABLE groups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE group_member (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users (id),
    group_id INTEGER REFERENCES groups (id)
);

CREATE TABLE jobs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    user_id INTEGER REFERENCES users (id),
    date_employment DATE DEFAULT NULL
);

CREATE INDEX users_id_index ON users (id);
CREATE INDEX groups_id_index ON groups (id);
CREATE INDEX group_member_id_index ON group_member (id);
CREATE INDEX group_member_user_id_index ON group_member (user_id);
CREATE INDEX group_member_group_id_index ON group_member (group_id);
CREATE INDEX jobs_id_index ON jobs (id);
CREATE INDEX jobs_user_id_index ON jobs (user_id);

INSERT INTO public.auth_users (name, password) VALUES ('admin', crypt('12345', gen_salt('bf')));

INSERT INTO users (name, age) VALUES ('Jack', 30);
INSERT INTO users (name, age) VALUES ('Oliver', 22);
INSERT INTO users (name, age) VALUES ('Harry', 18);
INSERT INTO users (name, age) VALUES ('Oscar', 39);
INSERT INTO users (name, age) VALUES ('Adam', 26);
INSERT INTO users (name, age) VALUES ('Carl', 48);
INSERT INTO groups (name) VALUES ('IT');
INSERT INTO groups (name) VALUES ('HR');
INSERT INTO groups (name) VALUES ('Support');
INSERT INTO jobs (name, user_id, date_employment) VALUES ('Developer', 1, CURRENT_DATE);
INSERT INTO jobs (name, user_id, date_employment) VALUES ('Help Desk', 1, CURRENT_DATE);
INSERT INTO jobs (name, user_id, date_employment) VALUES ('Senior HR Manager', 3, CURRENT_DATE);
INSERT INTO jobs (name, user_id, date_employment) VALUES ('Junior HR Manager', 4, CURRENT_DATE);
INSERT INTO jobs (name, user_id, date_employment) VALUES ('Manager', 3, CURRENT_DATE);
INSERT INTO jobs (name, user_id, date_employment) VALUES ('Сall-center Operator', 6, CURRENT_DATE);

INSERT INTO group_member (user_id, group_id) VALUES (1,1);
INSERT INTO group_member (user_id, group_id) VALUES (1,3);
INSERT INTO group_member (user_id, group_id) VALUES (3,2);
INSERT INTO group_member (user_id, group_id) VALUES (5,1);
INSERT INTO group_member (user_id, group_id) VALUES (6,3);
INSERT INTO group_member (user_id, group_id) VALUES (4,2);


